### ISSUE TITLE
MAJOR ISSUE: ConnectionResetError

### ISSUE THREAD

**Issue by Jules-NC** [Kernev/Apocryphe#9]
>/home/lambyor/anaconda3/bin/python /home/lambyor/Documents/Apocryphe/lapierousse/larousse_trad.py
Traceback (most recent call last):
  File "/home/lambyor/Documents/Apocryphe/lapierousse/larousse_trad.py", line 119, in <module>
    print(LarousseParser('man').feed())
  File "/home/lambyor/Documents/Apocryphe/lapierousse/larousse_trad.py", line 14, in __init__
    raw_data = raw_data.read().decode('utf8')
  File "/home/lambyor/anaconda3/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/home/lambyor/anaconda3/lib/python3.6/http/client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/lambyor/anaconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

MAJOR ERROR for data analysis. Must handle this.

**Comment by Jules-NC** [comment]
Done with: except Exception.
Bad but good !
